name: update-snapshots
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 8 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run update script
      run: ./scripts/update.sh
    - uses: actions/setup-go@v2
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Bumping packages to latest stable versions"
        title: "Bumping packages to latest stable versions"
        body: "Bumping packages to latest stable versions"
        branch: "update-snapshots"